"""Builds the WAG skill list, the T&T skill list and the example routines
(js/data/wag-skills.js, tt-skills.js, examples.js) from the JSON files in
tools/source/:

  wag_wg_skills.json   the WG (FIG) WAG Code of Points 2025-2028, from the
                       extractor in Dropbox Misc/Gymnastics/Reference/gym_skill_extract/WG WAG CoP Extraction
  Masters Vault Values.xlsx  UCG Masters vault values (Men / Women sheets)
  wag_ucg_skills.json  skills in the UCG WAG Code of Points (UCG additions to the
                       Xcel / WG skill lists), read from UCG/Code of Points/dist/UCG WAG CoP.pdf
  tt_skills.json       the UCG T&T DD charts (trampoline, double mini, tumbling),
                       including the UCG addendum's values
  examples.json        example routines: T&T (New / Intermediate / High Flyers)
                       and MAG (Developmental / Intermediate) Google Sheets

Run: python tools/build_data.py   (then commit the js/data files)
"""
import json
import os
import re

HERE = os.path.dirname(__file__)
SRC = os.path.join(HERE, "source")
OUT = os.path.join(HERE, "..", "js", "data")
POS = {"o": "tuck", "<": "pike", "/": "straight", "": ""}


def slug(s):
    s = s.replace("¾", " 3-4 ").replace("½", " 1-2 ").replace("¼", " 1-4 ")
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")[:60]


def write(name, header, var, rows):
    body = ",\n".join("  " + json.dumps(r, ensure_ascii=False) for r in rows)
    with open(os.path.join(OUT, name), "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        f.write(f"export const {var} = [\n{body}\n];\n")
    print(f"wrote js/data/{name}: {len(rows)}")


def wg_value(v):
    return v.split("=")[0] if "=" in v else v


def wag():
    rows = []
    for s in json.load(open(os.path.join(SRC, "wag_wg_skills.json"), encoding="utf-8")):
        if s["apparatus"] == "VT":
            continue
        rows.append({
            "id": f"WGW-{s['apparatus']}-{s['number']}-{s.get('variant', 1)}",
            "app": s["apparatus"].lower(),
            "name": " ".join(s["description"].split()),
            "eponym": s.get("eponym") or "",
            "value": wg_value(s["value"]),
            "group": int(s["element_group"]),  # WG element group 1-6
            "src": "WG",
            "note": "",
        })
    for s in json.load(open(os.path.join(SRC, "wag_ucg_skills.json"), encoding="utf-8")):
        if s["app"] == "vt":
            continue
        rows.append({
            "id": f"UCGW-{s['app'].upper()}-{s.get('num') or slug(s['name'])}",
            "app": s["app"],
            "name": " ".join(s["name"].split()),
            "eponym": s.get("eponym") or "",
            "value": s["value"],
            # USAG / Xcel element group number (UCG Infinity condenses these into I-IV)
            "group": int(s["group"]) if str(s.get("group") or "").isdigit() else None,
            "src": "UCG",
            "note": s.get("note") or "",
        })
    write("wag-skills.js", "// Generated by tools/build_data.py: WG WAG CoP 2025-2028 skills (wag_wg_skills.json) and UCG WAG CoP additions (wag_ucg_skills.json).\n// group: WG element group (WG skills) or USAG / Xcel element group (UCG skills).\n", "SKILLS", rows)


def wag_vaults():
    rows = []
    for s in json.load(open(os.path.join(SRC, "wag_wg_skills.json"), encoding="utf-8")):
        if s["apparatus"] != "VT":
            continue
        rows.append({"id": s["number"], "name": " ".join(s["description"].split()), "eponym": s.get("eponym") or "", "eg": s["element_group"], "value": float(s["value"]), "src": "WG"})
    write("wag-vaults.js", "// Generated by tools/build_data.py from tools/source/wag_wg_skills.json: WG WAG vault table 2025-2028.\n", "VAULTS", rows)
    return {r["id"]: r for r in rows}


# Masters vault table rows -> the WG vault(s) they correspond to. Rows not listed
# here (squat on, roll over, hechts, ...) aren't in the WG code: UCG Masters vaults.
MASTERS_MAP = {
    "Men": {
        "Front handspring": ["201"], "Front handspring with 1/2 twist": ["202"], "Front handspring with 1/1 twist": ["203"], "Front handspring with 3/2 twist": ["204"],
        "Front handspring and salto fwd. tucked": ["207"], "Front handspring and salto fwd. tucked with ½ twist": ["101"],
        "Front handspring and salto fwd. piked": ["213"], "Front handspring and salto fwd. piked with ½ twist": ["107"],
        "Front handspring and salto fwd. stretched": ["219"], "Front handspring and salto fwd. stretched wit ½ twist": ["113"],
        "Front handspring sw with 1/4 twist": ["301"], "Front handspring sw with 3/4 twist": ["302"], "Front handspring sw with 5/4 twist": ["303"],
        "Tsukahara or Yurchenko tucked": ["307", "507"], "Tsukahara or Yurchenko piked": ["308", "509"],
        "Tsukahara or Yurchenko tucked with 1/2 twist": ["309", "508"], "Tsukahara or Yurchenko tucked with 1/1 twist": ["119", "401"],
        "Tsukahara or Yurchenko stretched": ["313", "510"], "Tsukahara or Yurchenko stretched with 1/2 twist": ["314", "511"],
        "Tsukahara or Yurchenko stretched with 1/1 twist": ["125", "405"],
    },
    "Women": {
        "Front handspring": ["1.00"], "Front handspring with 1/2 twist": ["1.01"], "Front handspring with 1/1 twist": ["1.02"], "Front handspring with 3/2 twist": ["1.03"],
        "Front handspring with ½ twist 1st phase": ["1.20"], "Front handspring with ½ twist 1st phase and ½ twist 2nd": ["1.21"],
        "Yamashita": ["1.10"], "Yamashita 1/2 twist": ["1.11"], "Yamashita 1/1 twist": ["1.12"],
        "Front handspring and salto fwd. tucked": ["2.10"], "Front handspring and salto fwd. tucked with ½ twist": ["2.11"],
        "Front handspring and salto fwd. piked": ["2.20"], "Front handspring and salto fwd. piked with ½ twist": ["2.21"],
        "Yurchenko tucked": ["4.10"], "Yurchenko piked": ["4.20"], "Yurchenko tucked with 1/2 twist": ["4.11"], "Yurchenko tucked with 1/1 twist": ["4.12"],
        "Yurchenko stretched": ["4.30"], "Yurchenko stretched with 1/2 twist": ["4.31"], "Yurchenko stretched with 1/1 twist": ["4.32"],
        "Tsukahara tucked": ["3.10"], "Tsukahara piked": ["3.20"], "Tsukahara tucked with 1/2 twist": ["3.11"], "Tsukahara tucked with 1/1 twist": ["3.12"],
        "Tsukahara stretched": ["3.30"], "Tsukahara stretched with 1/2 twist": ["3.31"], "Tsukahara stretched with 1/1 twist": ["3.32"],
    },
}


def masters_vaults(wag_by_id):
    """Write the Masters vaults that aren't in the WG code, and check the rest of
    the Masters table against the WG vault values."""
    import openpyxl
    text = open(os.path.join(OUT, "mag-vaults.js"), encoding="utf-8").read()
    mag_by_id = {v["id"]: v for v in json.loads(text[text.index("["): text.rindex("]") + 1])}
    wb = openpyxl.load_workbook(os.path.join(SRC, "Masters Vault Values.xlsx"), data_only=True)
    rows, problems = [], []
    for sheet, disc, by_id in (("Men", "mag", mag_by_id), ("Women", "wag", wag_by_id)):
        for r in list(wb[sheet].iter_rows(values_only=True))[4:]:
            name, value = (r[1] or "").strip(), r[2]
            if not name or value is None:
                continue
            ids = MASTERS_MAP[sheet].get(name)
            if ids:
                for i in ids:
                    wg = by_id.get(i)
                    if not wg or abs(wg["value"] - float(value)) > 1e-9:
                        problems.append(f"{sheet}: {name} = {value}, WG {i} = {wg and wg['value']}")
                continue
            rows.append({"id": f"UCGM-{disc}-{slug(name)}", "disc": disc, "name": name, "value": float(value), "src": "UCG",
                         "flipping": bool(re.search(r"(?i)salto|tsuk|yurch", name))})
    for p in problems:
        print("  MASTERS VAULT CHECK:", p)
    write("masters-vaults.js", "// Generated by tools/build_data.py from tools/source/Masters Vault Values.xlsx: Masters vaults that aren't in the WG code.\n// The table's other vaults were checked against the WG vault tables, which the planner uses for them.\n", "VAULTS", rows)


def norm(name):
    n = re.sub(r"[^a-z0-9/ ]+", " ", name.lower().replace("¾", " 3/4 ").replace("½", " 1/2 ").replace("porpise", "porpoise"))
    n = re.sub(r"\b(back|front) (tuck|pike|straight|layout)\b", r"\1 somersault \2", n)
    n = n.replace("layout", "straight").replace("stepout", "step out").replace("step-out", "step out")
    return " ".join(n.split())


TT_ROWS = []


def tt():
    data = json.load(open(os.path.join(SRC, "tt_skills.json"), encoding="utf-8"))
    rows = []
    for key, apps in (("tramp", ["tr"]), ("dmt", ["dmt"])):
        for s in data[key]:
            for pos, dd in s["positions"].items():
                name = s["name"].strip()
                label = f"{name} {POS.get(pos, pos)}".strip() if len(s["positions"]) > 1 else name
                for app in apps:
                    rows.append({
                        "id": f"TT-{app}-{slug(label)}-{slug(s.get('fig', '') + pos) or 'x'}",
                        "app": app,
                        "name": label,
                        "notation": f"{s.get('fig', '')}{pos}".strip(),
                        "dd": dd,
                        "src": "UCG",
                    })
    for s in data["tumbling"]:
        rows.append({
            "id": f"TT-tu-{slug(s['name'])}",
            "app": "tu",
            "name": s["name"].strip(),
            "notation": s.get("symbol", ""),
            "dd": s["dd"],
            "src": "UCG",
        })
    seen = set()
    rows = [r for r in rows if not (r["id"] in seen or seen.add(r["id"]))]
    TT_ROWS[:] = rows
    write("tt-skills.js", "// Generated by tools/build_data.py from tools/source/tt_skills.json (UCG T&T DD charts).\n// notation: FIG shorthand; dd: difficulty.\n", "SKILLS", rows)


def match_tt(app, skill):
    """Fill in shorthand (and the skill id) for an example skill found in the DD charts."""
    app = "tr" if app == "sy" else app
    key = norm(skill.get("name", ""))
    for cand in (key, f"{key} tuck"):
        for r in TT_ROWS:
            if r["app"] == app and norm(r["name"]) == cand:
                # The chart's DD wins: several example sheets predate the UCG addendum.
                return {**skill, "notation": skill.get("notation") or r["notation"], "dd": r["dd"], "skillId": r["id"]}
    return skill


def examples():
    rows = []
    stale = re.compile(r"(?i)sheet note: (-1 for each skill fewer than 6|sv cap is [\d.]+)\.?")
    for e in json.load(open(os.path.join(SRC, "examples.json"), encoding="utf-8")):
        r = {"id": e["id"], "disc": e["discipline"], "level": e["level"], "event": e["event"], "title": e["title"]}
        if "skills" in e:
            if e["discipline"] == "tt":
                r["skills"] = [match_tt(e["event"], {"name": s.get("name", ""), "notation": s.get("notation", ""), "dd": s.get("dd", "")}) for s in e["skills"]]
            else:
                r["skills"] = [{"name": s.get("name", ""), "letter": s.get("letter", ""), "eg": str(s["eg"]) if s.get("eg") else ""} for s in e["skills"]]
        if "passes" in e:
            r["passes"] = [[match_tt(e["event"], {"name": s.get("name", ""), "notation": s.get("notation", ""), "dd": s.get("dd", "")}) for s in p] for p in e["passes"]]
        if e.get("vaultNumber"):
            r["vault"] = str(e["vaultNumber"])
        note = stale.sub("", e.get("note", "")).strip()
        if note:
            r["note"] = note
        if e.get("video"):
            r["video"] = e["video"]
        rows.append(r)
    write("examples.js", "// Generated by tools/build_data.py from tools/source/examples.json (UCG example routine sheets).\n", "EXAMPLES", rows)


if __name__ == "__main__":
    wag()
    masters_vaults(wag_vaults())
    tt()
    examples()
