"""Builds the WAG skill list, the T&T skill list and the example routines
(js/data/wag-skills.js, tt-skills.js, examples.js) from the JSON files in
tools/source/:

  wag_ucg_skills.json  skills in the UCG WAG Code of Points (UCG additions to the
                       Xcel / WG skill lists), read from UCG/Code of Points/dist/UCG WAG CoP.pdf
  tt_skills.json       the UCG T&T DD charts (trampoline, double mini, tumbling),
                       including the UCG addendum's values
  examples.json        example routines: T&T (New / Intermediate / High Flyers)
                       and MAG (Developmental / Intermediate) Google Sheets

Run: python tools/build_data.py   (then commit the js/data files)
"""
import json
import os
import re

HERE = os.path.dirname(__file__)
SRC = os.path.join(HERE, "source")
OUT = os.path.join(HERE, "..", "js", "data")
POS = {"o": "tuck", "<": "pike", "/": "straight", "": ""}


def slug(s):
    s = s.replace("¾", " 3-4 ").replace("½", " 1-2 ").replace("¼", " 1-4 ")
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")[:60]


def write(name, header, var, rows):
    body = ",\n".join("  " + json.dumps(r, ensure_ascii=False) for r in rows)
    with open(os.path.join(OUT, name), "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        f.write(f"export const {var} = [\n{body}\n];\n")
    print(f"wrote js/data/{name}: {len(rows)}")


def wag():
    rows = []
    for s in json.load(open(os.path.join(SRC, "wag_ucg_skills.json"), encoding="utf-8")):
        if s["app"] == "vt":
            continue
        rows.append({
            "id": f"UCGW-{s['app'].upper()}-{s.get('num') or slug(s['name'])}",
            "app": s["app"],
            "name": " ".join(s["name"].split()),
            "eponym": s.get("eponym") or "",
            "value": s["value"],
            # USAG / Xcel element group number (UCG Infinity condenses these into I-IV)
            "group": int(s["group"]) if str(s.get("group") or "").isdigit() else None,
            "src": "UCG",
            "note": s.get("note") or "",
        })
    write("wag-skills.js", "// Generated by tools/build_data.py from tools/source/wag_ucg_skills.json (UCG WAG CoP additions).\n", "SKILLS", rows)


def norm(name):
    n = re.sub(r"[^a-z0-9/ ]+", " ", name.lower().replace("¾", " 3/4 ").replace("½", " 1/2 ").replace("porpise", "porpoise"))
    n = re.sub(r"\b(back|front) (tuck|pike|straight|layout)\b", r"\1 somersault \2", n)
    n = n.replace("layout", "straight").replace("stepout", "step out").replace("step-out", "step out")
    return " ".join(n.split())


TT_ROWS = []


def tt():
    data = json.load(open(os.path.join(SRC, "tt_skills.json"), encoding="utf-8"))
    rows = []
    for key, apps in (("tramp", ["tr"]), ("dmt", ["dmt"])):
        for s in data[key]:
            for pos, dd in s["positions"].items():
                name = s["name"].strip()
                label = f"{name} {POS.get(pos, pos)}".strip() if len(s["positions"]) > 1 else name
                for app in apps:
                    rows.append({
                        "id": f"TT-{app}-{slug(label)}-{slug(s.get('fig', '') + pos) or 'x'}",
                        "app": app,
                        "name": label,
                        "notation": f"{s.get('fig', '')}{pos}".strip(),
                        "dd": dd,
                        "src": "UCG",
                    })
    for s in data["tumbling"]:
        rows.append({
            "id": f"TT-tu-{slug(s['name'])}",
            "app": "tu",
            "name": s["name"].strip(),
            "notation": s.get("symbol", ""),
            "dd": s["dd"],
            "src": "UCG",
        })
    seen = set()
    rows = [r for r in rows if not (r["id"] in seen or seen.add(r["id"]))]
    TT_ROWS[:] = rows
    write("tt-skills.js", "// Generated by tools/build_data.py from tools/source/tt_skills.json (UCG T&T DD charts).\n// notation: FIG shorthand; dd: difficulty.\n", "SKILLS", rows)


def match_tt(app, skill):
    """Fill in shorthand (and the skill id) for an example skill found in the DD charts."""
    app = "tr" if app == "sy" else app
    key = norm(skill.get("name", ""))
    for cand in (key, f"{key} tuck"):
        for r in TT_ROWS:
            if r["app"] == app and norm(r["name"]) == cand:
                return {**skill, "notation": skill.get("notation") or r["notation"], "skillId": r["id"]}
    return skill


def examples():
    rows = []
    stale = re.compile(r"(?i)sheet note: (-1 for each skill fewer than 6|sv cap is [\d.]+)\.?")
    for e in json.load(open(os.path.join(SRC, "examples.json"), encoding="utf-8")):
        r = {"id": e["id"], "disc": e["discipline"], "level": e["level"], "event": e["event"], "title": e["title"]}
        if "skills" in e:
            if e["discipline"] == "tt":
                r["skills"] = [match_tt(e["event"], {"name": s.get("name", ""), "notation": s.get("notation", ""), "dd": s.get("dd", "")}) for s in e["skills"]]
            else:
                r["skills"] = [{"name": s.get("name", ""), "letter": s.get("letter", ""), "eg": str(s["eg"]) if s.get("eg") else ""} for s in e["skills"]]
        if "passes" in e:
            r["passes"] = [[match_tt(e["event"], {"name": s.get("name", ""), "notation": s.get("notation", ""), "dd": s.get("dd", "")}) for s in p] for p in e["passes"]]
        if e.get("vaultNumber"):
            r["vault"] = str(e["vaultNumber"])
        note = stale.sub("", e.get("note", "")).strip()
        if note:
            r["note"] = note
        if e.get("video"):
            r["video"] = e["video"]
        rows.append(r)
    write("examples.js", "// Generated by tools/build_data.py from tools/source/examples.json (UCG example routine sheets).\n", "EXAMPLES", rows)


if __name__ == "__main__":
    wag()
    tt()
    examples()
